Criar header container card navegacao lateral
riltonbispo/Catalogo-de-jogos pull request #16
Opened 2023-10-14 20:51 UTC by Douglas-Dauto

Implementado página home.

2023-10-14 21:13 UTC, riltonbispo requested changes
Alterações

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +        </ul>
os elementos não são uma lista, não precisa ficar em um `ul` .

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +                        <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.00
exportar o icone do figma com `svg `e usar a `tag` imagem, para evitar poluição do `html`

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +                        <path fill-rule="evenodd" d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
exportar o icone do figma com `svg `e usar a `tag` imagem, para evitar poluição do `html`

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +                        <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-
exportar o icone do figma com `svg `e usar a `tag` imagem, para evitar poluição do `html`

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
exportar o icone do figma com `svg `e usar a `tag` imagem, para evitar poluição do `html`

2023-10-14 21:13 UTC, riltonbispo commented on src/assets/styles/home.css
> +    text-transform: capitalize;
o estilo dos button ja estão prontos, só usar a classe:
![image](https://github.com/riltonbispo/Catalogo-de-jogos/assets/98268946/8cfae192-d8b1-414e-aa45-032b17604ad3)

2023-10-14 21:13 UTC, riltonbispo commented on src/home.html
> +            <li>Echo</li>
usar a imagem da logo

2023-10-15 14:25 UTC, Douglas-Dauto commented on src/home.html
> +        </ul>
Feito.

2023-10-15 14:37 UTC, Douglas-Dauto commented on src/home.html
> +                        <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.00
Feito.

2023-10-15 14:37 UTC, Douglas-Dauto commented on src/home.html
> +                        <path fill-rule="evenodd" d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
Feito.

2023-10-15 14:38 UTC, Douglas-Dauto commented on src/home.html
> +                        <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-
Feito.

2023-10-15 14:38 UTC, Douglas-Dauto commented on src/home.html
> +                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
Feito.

2023-10-15 15:24 UTC, Douglas-Dauto commented on src/assets/styles/home.css
> +    text-transform: capitalize;
Feito.

2023-10-15 15:24 UTC, Douglas-Dauto commented on src/home.html
> +            <li>Echo</li>
Feito.

2023-10-16 14:36 UTC, riltonbispo approved these changes

2023-10-16 14:42 UTC, merged